#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI"

# Colorize commands when possible.
alias \
	ls="exa --group-directories-first --icons" \
	grep="grep --color=auto" \
	diff="diff --color=auto"

alias \
    bare='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

alias \
    tl="tmux ls" \
    ta="tmux attach-session -t" \
    tk="tmux kill-session -t"

alias \
    clean="make clean && rm -rf config.h"
