#!/bin/sh
TEMP=$(sensors | awk '/Tctl:/ {print int($2)}')

if [ $TEMP -ge 0 ] && [ $TEMP -le 50 ]; then
    echo -e "<span color='#EBCB8B'></span> : $TEMP°C\n"
elif [ $TEMP -ge 51 ] && [ $TEMP -le 70 ]; then
    echo -e "<span color='#D08770'></span> : $TEMP°C\n"
elif [ $TEMP -ge 71 ]; then
    echo -e "<span color='#BF616A'></span> : $TEMP°C\n"
else
    echo "UNKNWN"
fi
