#!/bin/sh

## Start GNOME Keyring
eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &

#export XDG_SESSION_TYPE=x11
#export GDK_BACKEND=x11
#exec gnome-session

#ssh-agent dwm
ssh-agent i3
