#!/bin/sh

## Start GNOME Keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)
export SSH_AUTH_SOCK

xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &

#export XDG_SESSION_TYPE=x11
#export GDK_BACKEND=x11
#exec gnome-session

ssh-agent dwm
